name: Test Module
description: Test Module
inputs:
  github_app_token:
    description: 'GitHub Access Token'
    required: true

  github_token:
    description: 'GitHub Access Token'
    required: false
    default: ${{ github.token }}
runs:
  using: composite
  steps:
    - run: github-comment exec -- terraform init
      shell: bash
      working-directory: ${{ env.TFACTION_TARGET }}
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}

    - uses: suzuki-shunsuke/github-action-format@v0.1.1
      with:
        working_directory: ${{ env.TFACTION_TARGET }}
        github_token: ${{ inputs.github_app_token }}
        command: terraform-docs . > README.md
        commit_message: 'docs(${{ env.TFACTION_TARGET }}): generate Terraform Module document by terraform-docs'

    - uses: suzuki-shunsuke/github-action-terraform-fmt@v0.1.1
      with:
        working_directory: ${{ env.TFACTION_TARGET }}
        github_token: ${{ inputs.github_app_token }}

    - run: github-comment exec -var "target:${TFACTION_TARGET}" -- terraform validate
      working-directory: ${{ env.TFACTION_TARGET }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}

    - uses: suzuki-shunsuke/github-action-tfsec@v0.1.5
      with:
        github_token: ${{ inputs.github_token }}
        working_directory: ${{ env.TFACTION_TARGET }}
        github_comment: 'true'

    - uses: suzuki-shunsuke/github-action-tflint@v0.1.4
      with:
        github_token: ${{ inputs.github_token }}
        working_directory: ${{ env.TFACTION_TARGET }}
        github_comment: 'true'
