name: Exports secrets as environment variables
description: Exports secrets as environment variables
inputs:
  secrets:
    description: 'secrets context'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
