name: List Working Directories
description: List Working Directories
inputs:
  file:
    description: 'file name'
    required: false
    default: ci.yaml
  base_directory:
    description: 'base directory'
    required: false
    default: '.'
outputs:
  file:
    description: Output file path
    value: ${{ steps.main.outputs.file }}
runs:
  using: composite
  steps:
  - run: |
      tempfile=$(mktemp)
      git ls-files "${{ inputs.base_directory }}" | grep -E "/${{ inputs.file }}$" > "$tempfile"
      echo "::set-output name=file::$tempfile"
    shell: bash
    id: main
