name: List Working Directories
description: List Working Directories
outputs:
  file:
    description: Output file path
    value: ${{ steps.main.outputs.file }}
runs:
  using: composite
  steps:
    - uses: suzuki-shunsuke/tfaction/get-global-config@v0.4.3
      id: global-config
    - run: |
        tempfile=$(mktemp)
        git ls-files "${{ steps.global-config.outputs.base_working_directory }}" | grep -E "/${{ steps.global-config.outputs.working_directory_file }}$" > "$tempfile"
        echo "::set-output name=file::$tempfile"
      shell: bash
      id: main
