name: Create a pull request to scaffold a working directory
description: Create a pull request to scaffold a working directory
inputs:
  github_app_token:
    description: 'GitHub Access Token'
    required: true
runs:
  using: composite
  steps:
    - uses: suzuki-shunsuke/tfaction/get-target-config@main
      id: target-config
      env:
        TFACTION_IS_APPLY: "false"

    - run: git add .
      shell: bash
      working-directory: ${{steps.target-config.outputs.working_directory}}
    - run: |
        echo "::set-output name=branch::scaffold-working-diretory/${TFACTION_TARGET}/$(date +%Y%m%dT%H%M%S)"
      id: branch
      shell: bash

    - run: |
        git diff --cached --name-only "${{steps.target-config.outputs.working_directory}}" |
          xargs ghcp commit -r "$GITHUB_REPOSITORY" \
            -b "${{steps.branch.outputs.branch}}" \
            -m "scaffold a working directory (${TFACTION_TARGET})"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_app_token }}

    - run: |
        gh pr create \
          -H "${{steps.branch.outputs.branch}}" \
          -a "$GITHUB_ACTOR" \
          -t "Scaffold a working directory (${TFACTION_TARGET})" \
          -b "This pull request was created by GitHub Actions workflow_dispatch event https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_app_token }}
