name: Create a pull request to scaffold a working directory
description: Create a pull request to scaffold a working directory
inputs:
  target:
    description: 'Target'
    required: true
  github_app_token:
    description: 'GitHub Access Token'
    required: true
  working_directory:
    description: 'Working Directory'
    required: true
runs:
  using: composite
  steps:
    - run: git add .
      shell: bash
      working-directory: ${{inputs.working_directory}}
    - run: |
        echo "::set-output name=branch::scaffold-working-diretory/${{inputs.target}}/$(date +%Y%m%dT%H%M%S)"
      id: branch
      shell: bash

    - run: |
        git diff --cached --name-only "${{inputs.working_directory}}" |
          xargs ghcp commit -r "$GITHUB_REPOSITORY" \
            -b "${{steps.branch.outputs.branch}}" \
            -m "scaffold a working directory (${{inputs.target}})"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.event.outputs.token }}
    - run: |
        ghcp pull-request -r "$GITHUB_REPOSITORY" \
          -b "${{steps.branch.outputs.branch}}" \
          --title "Scaffold a working directory (${{inputs.target}})" \
          --body "This pull request was created by GitHub Actions workflow_dispatch event https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_app_token }}
