name: Get global configuration
description: Get global configuration
outputs:
  base_working_directory:
    description: base directory of working directories
  working_directory_file:
    description: file name which locates on working directories
  renovate_login:
    description: Renovate login
  label_prefix_target:
    description: label prefix for target
  label_prefix_tfmigrate:
    description: label prefix for tfmigrate
  label_prefix_skip:
    description: label prefix to skip terraform plan and apply
  skip_create_pr:
    description: Whether skip creating pull requests
runs:
  using: 'node16'
  main: 'dist/index.js'
