name: List targets
description: List targets
inputs:
  github_token:
    description: 'GitHub Access Token'
    required: false
    default: ${{ github.token }}
outputs:
  tfmigrate_targets:
    description: list of tfmigrate targets
    value: ${{ steps.list-targets.outputs.tfmigrate_targets }}
  terraform_targets:
    description: list of terraform targets
    value: ${{ steps.list-targets.outputs.terraform_targets }}
runs:
  using: composite
  steps:
    - run: github-comment exec -- ci-info run | sed "s/^export //" >> "$GITHUB_ENV"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
    - uses: suzuki-shunsuke/tfaction/list-working-dirs@v0.4.10-1
      id: list-working-directory-configs
    - uses: suzuki-shunsuke/tfaction/list-targets-with-changed-files@v0.4.10-1
      id: list-targets
      with:
        changed_files: ${{ env.CI_INFO_TEMP_DIR }}/pr_all_filenames.txt
        labels: ${{ env.CI_INFO_TEMP_DIR }}/labels.txt
        pull_request: ${{ env.CI_INFO_TEMP_DIR }}/pr.json
        config_files: ${{ steps.list-working-directory-configs.outputs.file }}
