name: terraform apply
description: terraform apply
inputs:
  target:
    description: 'target'
    required: true
  github_app_token:
    description: 'GitHub Access Token'
    required: true
  s3_bucket_name_plan_file:
    description: 'S3 Bucket Name to store Terraform Plan File'
    required: true

  github_token:
    description: 'GitHub Access Token'
    required: false
    default: ${{ github.token }}
  working_directory:
    description: 'Working Directory'
    required: false
    default: ''
runs:
  using: composite
  steps:
    - run: bash ${{ github.action_path }}/main.sh
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GITHUB_APP_TOKEN: ${{ inputs.github_app_token }}
        TF_VAR_github_token: ${{ inputs.github_app_token }}
        TARGET: ${{ inputs.target }}
        S3_BUCKET_NAME_PLAN_FILE: ${{ inputs.s3_bucket_name_plan_file }}
