name: tfmigrate apply
description: tfmigrate apply
inputs:
  github_app_token:
    description: 'GitHub Access Token'
    required: true

  target:
    description: 'target'
    required: false
    default: ''
  github_token:
    description: 'GitHub Access Token'
    required: false
    default: ${{ github.token }}
  working_directory:
    description: 'Working Directory'
    required: false
    default: ''
runs:
  using: composite
  steps:
    - run: bash ${{ github.action_path }}/main.sh
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GITHUB_APP_TOKEN: ${{ inputs.github_app_token }}
        TARGET: ${{ inputs.target }}
