name: setup
description: setup
inputs:
  github_app_token:
    description: 'GitHub Access Token'
    required: true

  github_token:
    description: 'GitHub Access Token'
    required: false
    default: ${{ github.token }}
  ssh_key:
    description: 'SSH Key for Terraform Private Module'
    required: false
outputs:
  working_directory:
    description: working directory
    value: ${{ steps.target-config.outputs.working_directory }}
  s3_bucket_name_plan_file:
    description: S3 Buckte name for plan files
    value: ${{ steps.target-config.outputs.s3_bucket_name_plan_file}}
  s3_bucket_name_tfmigrate_history:
    description: S3 Buckte name for tfmigrate history files
    value: ${{ steps.target-config.outputs.s3_bucket_name_tfmigrate_history}}
runs:
  using: composite
  steps:
    - uses: suzuki-shunsuke/tfaction/get-target-config@v0.2.1
      id: target-config

    - run: aqua i -l -a
      shell: bash
      working-directory: ${{ steps.target-config.outputs.working_directory }}

    - run: github-comment exec -- ci-info run | sed "s/^export //" >> "$GITHUB_ENV"
      shell: bash

    - uses: aws-actions/configure-aws-credentials@v1.6.1
      if: steps.target-config.outputs.aws_assume_role_arn != ''
      with:
        role-to-assume: ${{ steps.target-config.outputs.aws_assume_role_arn }}
        role-session-name: samplerolesession
        aws-region: ${{ steps.target-config.outputs.aws_region }}

    - uses: google-github-actions/auth@v0
      if: steps.target-config.outputs.gcp_service_account != ''
      with:
        workload_identity_provider: ${{ steps.target-config.outputs.gcp_workload_identity_provider }}
        service_account: ${{ steps.target-config.outputs.gcp_service_account }}

    - uses: suzuki-shunsuke/tfaction/deploy-ssh-key@v0.2.1
      if: inputs.ssh_key != ''
      with:
       ssh_key: ${{ inputs.ssh_key }}

    - uses: suzuki-shunsuke/github-action-terraform-init@v0.1.3
      with:
        working_directory: ${{ steps.target-config.outputs.working_directory }}
        github_token: ${{ inputs.github_token }}
        github_app_token: ${{ inputs.github_app_token }}
